// <auto-generated />
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310214149_first50word")]
    partial class first50word
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .UseCollation("Turkish_CS_AS");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.Models.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EngWordName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TurWordName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EngWordName = "Apple",
                            Picture = "apple.jpg",
                            TurWordName = "Elma"
                        },
                        new
                        {
                            Id = 2,
                            EngWordName = "Book",
                            Picture = "book.jpg",
                            TurWordName = "Kitap"
                        },
                        new
                        {
                            Id = 3,
                            EngWordName = "Car",
                            Picture = "car.jpg",
                            TurWordName = "Araba"
                        },
                        new
                        {
                            Id = 4,
                            EngWordName = "Dog",
                            Picture = "dog.jpg",
                            TurWordName = "Köpek"
                        },
                        new
                        {
                            Id = 5,
                            EngWordName = "Cat",
                            Picture = "cat.jpg",
                            TurWordName = "Kedi"
                        },
                        new
                        {
                            Id = 6,
                            EngWordName = "House",
                            Picture = "house.jpg",
                            TurWordName = "Ev"
                        },
                        new
                        {
                            Id = 7,
                            EngWordName = "Water",
                            Picture = "water.jpg",
                            TurWordName = "Su"
                        },
                        new
                        {
                            Id = 8,
                            EngWordName = "Fire",
                            Picture = "fire.jpg",
                            TurWordName = "Ateş"
                        },
                        new
                        {
                            Id = 9,
                            EngWordName = "Tree",
                            Picture = "tree.jpg",
                            TurWordName = "Ağaç"
                        },
                        new
                        {
                            Id = 10,
                            EngWordName = "Sun",
                            Picture = "sun.jpg",
                            TurWordName = "Güneş"
                        },
                        new
                        {
                            Id = 11,
                            EngWordName = "Moon",
                            Picture = "moon.jpg",
                            TurWordName = "Ay"
                        },
                        new
                        {
                            Id = 12,
                            EngWordName = "Star",
                            Picture = "star.jpg",
                            TurWordName = "Yıldız"
                        },
                        new
                        {
                            Id = 13,
                            EngWordName = "Bird",
                            Picture = "bird.jpg",
                            TurWordName = "Kuş"
                        },
                        new
                        {
                            Id = 14,
                            EngWordName = "Fish",
                            Picture = "fish.jpg",
                            TurWordName = "Balık"
                        },
                        new
                        {
                            Id = 15,
                            EngWordName = "Flower",
                            Picture = "flower.jpg",
                            TurWordName = "Çiçek"
                        },
                        new
                        {
                            Id = 16,
                            EngWordName = "Computer",
                            Picture = "computer.jpg",
                            TurWordName = "Bilgisayar"
                        },
                        new
                        {
                            Id = 17,
                            EngWordName = "Phone",
                            Picture = "phone.jpg",
                            TurWordName = "Telefon"
                        },
                        new
                        {
                            Id = 18,
                            EngWordName = "Table",
                            Picture = "table.jpg",
                            TurWordName = "Masa"
                        },
                        new
                        {
                            Id = 19,
                            EngWordName = "Chair",
                            Picture = "chair.jpg",
                            TurWordName = "Sandalye"
                        },
                        new
                        {
                            Id = 20,
                            EngWordName = "Door",
                            Picture = "door.jpg",
                            TurWordName = "Kapı"
                        },
                        new
                        {
                            Id = 21,
                            EngWordName = "Window",
                            Picture = "window.jpg",
                            TurWordName = "Pencere"
                        },
                        new
                        {
                            Id = 22,
                            EngWordName = "Bed",
                            Picture = "bed.jpg",
                            TurWordName = "Yatak"
                        },
                        new
                        {
                            Id = 23,
                            EngWordName = "Lamp",
                            Picture = "lamp.jpg",
                            TurWordName = "Lamba"
                        },
                        new
                        {
                            Id = 24,
                            EngWordName = "Pen",
                            Picture = "pen.jpg",
                            TurWordName = "Kalem"
                        },
                        new
                        {
                            Id = 25,
                            EngWordName = "Pencil",
                            Picture = "pencil.jpg",
                            TurWordName = "Kurşun Kalem"
                        },
                        new
                        {
                            Id = 26,
                            EngWordName = "Eraser",
                            Picture = "eraser.jpg",
                            TurWordName = "Silgi"
                        },
                        new
                        {
                            Id = 27,
                            EngWordName = "Ruler",
                            Picture = "ruler.jpg",
                            TurWordName = "Cetvel"
                        },
                        new
                        {
                            Id = 28,
                            EngWordName = "Bag",
                            Picture = "bag.jpg",
                            TurWordName = "Çanta"
                        },
                        new
                        {
                            Id = 29,
                            EngWordName = "Shoe",
                            Picture = "shoe.jpg",
                            TurWordName = "Ayakkabı"
                        },
                        new
                        {
                            Id = 30,
                            EngWordName = "Sock",
                            Picture = "sock.jpg",
                            TurWordName = "Çorap"
                        },
                        new
                        {
                            Id = 31,
                            EngWordName = "Shirt",
                            Picture = "shirt.jpg",
                            TurWordName = "Gömlek"
                        },
                        new
                        {
                            Id = 32,
                            EngWordName = "Pants",
                            Picture = "pants.jpg",
                            TurWordName = "Pantolon"
                        },
                        new
                        {
                            Id = 33,
                            EngWordName = "Hat",
                            Picture = "hat.jpg",
                            TurWordName = "Şapka"
                        },
                        new
                        {
                            Id = 34,
                            EngWordName = "Glove",
                            Picture = "glove.jpg",
                            TurWordName = "Eldiven"
                        },
                        new
                        {
                            Id = 35,
                            EngWordName = "Scarf",
                            Picture = "scarf.jpg",
                            TurWordName = "Atkı"
                        },
                        new
                        {
                            Id = 36,
                            EngWordName = "Coat",
                            Picture = "coat.jpg",
                            TurWordName = "Mont"
                        },
                        new
                        {
                            Id = 37,
                            EngWordName = "Rain",
                            Picture = "rain.jpg",
                            TurWordName = "Yağmur"
                        },
                        new
                        {
                            Id = 38,
                            EngWordName = "Snow",
                            Picture = "snow.jpg",
                            TurWordName = "Kar"
                        },
                        new
                        {
                            Id = 39,
                            EngWordName = "Wind",
                            Picture = "wind.jpg",
                            TurWordName = "Rüzgar"
                        },
                        new
                        {
                            Id = 40,
                            EngWordName = "Cloud",
                            Picture = "cloud.jpg",
                            TurWordName = "Bulut"
                        },
                        new
                        {
                            Id = 41,
                            EngWordName = "Sky",
                            Picture = "sky.jpg",
                            TurWordName = "Gökyüzü"
                        },
                        new
                        {
                            Id = 42,
                            EngWordName = "Mountain",
                            Picture = "mountain.jpg",
                            TurWordName = "Dağ"
                        },
                        new
                        {
                            Id = 43,
                            EngWordName = "River",
                            Picture = "river.jpg",
                            TurWordName = "Nehir"
                        },
                        new
                        {
                            Id = 44,
                            EngWordName = "Sea",
                            Picture = "sea.jpg",
                            TurWordName = "Deniz"
                        },
                        new
                        {
                            Id = 45,
                            EngWordName = "Ocean",
                            Picture = "ocean.jpg",
                            TurWordName = "Okyanus"
                        },
                        new
                        {
                            Id = 46,
                            EngWordName = "Beach",
                            Picture = "beach.jpg",
                            TurWordName = "Plaj"
                        },
                        new
                        {
                            Id = 47,
                            EngWordName = "Sand",
                            Picture = "sand.jpg",
                            TurWordName = "Kum"
                        },
                        new
                        {
                            Id = 48,
                            EngWordName = "Rock",
                            Picture = "rock.jpg",
                            TurWordName = "Kaya"
                        },
                        new
                        {
                            Id = 49,
                            EngWordName = "Soil",
                            Picture = "soil.jpg",
                            TurWordName = "Toprak"
                        },
                        new
                        {
                            Id = 50,
                            EngWordName = "Grass",
                            Picture = "grass.jpg",
                            TurWordName = "Çimen"
                        });
                });

            modelBuilder.Entity("Backend.Models.WordSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Samples")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WordID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WordID");

                    b.ToTable("WordSamples");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Samples = "I eat an apple every day.",
                            WordID = 1
                        });
                });

            modelBuilder.Entity("Backend.Models.WordSample", b =>
                {
                    b.HasOne("Backend.Models.Word", "Word")
                        .WithMany("WordSamples")
                        .HasForeignKey("WordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("Backend.Models.Word", b =>
                {
                    b.Navigation("WordSamples");
                });
#pragma warning restore 612, 618
        }
    }
}
