services:
  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=Project;User Id=sa;Password=Your_password123;TrustServerCertificate=True;MultipleActiveResultSets=true
    restart: unless-stopped

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlvolume:
