services:
  api:
    build: ./backend
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=testdb;User=sa;Password=Your_password123;

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  # volumes:
  #   sqlvolume:
  backend:
    build: ./backend/backend/
    ports:
      - "5000:8080"
    depends_on:
      db:
        condition: service_healthy
      # - dbs
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=testdb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;Encrypt=False;
